do/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stori/', include('stori.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stori/urls.py
from django.urls import path
from . import views


app_name = 'stori'

urlpatterns = [
	path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('congrats', views.congrats, name='congrats'),
    path('save', views.save, name='save'),
    path('account', views.account, name='account'),
    path('login', views.login, name='login'),
]

stori/models.py
from django.db import models
from django.urls import reverse
from datetime import date


class Member(models.Model):
	full_name = models.CharField(max_length=250, blank=True)
	email = models.EmailField(max_length=250, blank=True)
	gender = models.CharField(max_length=250, blank=True)
	date_birth = models.DateField(null=True, blank=True)
	phone_number = models.CharField(max_length=250, default='0244231035', blank=True)
	address = models.CharField(max_length=250, blank=True)
	town_city = models.CharField(max_length=250, blank=True)
	country = models.CharField(max_length=250, blank=True)
	occupation = models.CharField(max_length=250, blank=True)
	pics = models.ImageField(default = 'default.jpg')


	def __str__(self):
		return self.full_name + '|' + self.phone_number

class Account(models.Model):
 	year = models.CharField(max_length=250, null=True, blank=True)	
 	month = models.CharField(max_length=250, null=True, blank=True)
 	offering_gotten = models.CharField(max_length=250, null=True, blank=True)	
 	offering_welfare = models.CharField(max_length=250, null=True, blank=True)
 	outstanding_offering = models.CharField(max_length=250, null=True, blank=True)	

 	def __str__(self):
 		return self.outstanding_offering


class Week(models.Model):
 	account = models.ForeignKey(Account, on_delete=models.CASCADE)
 	week1 = models.CharField(max_length=250, null=True, blank=True)
 	week2 = models.CharField(max_length=250, null=True, blank=True)
 	week3 = models.CharField(max_length=250, null=True, blank=True)
 	week4 = models.CharField(max_length=250, null=True, blank=True)






	

stori/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import  ModelForm
from .models import Member
#from django.forms import extras

#class SignUpForm(UserCreationForm):
   
   # class Meta:
   #     model = User
   #     fields = ('username','password1')


class MemberForm(ModelForm):
	

	class Meta:
		model = Member
		fields = ['full_name', 'email', 'gender', 'date_birth', 'phone_number', 'address', 'town_city', 'country', 'occupation']















stori/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Member
from .forms import MemberForm



def index(request):
	return render(request, 'stori/base.html')


def register(request):
	return render(request, 'stori/register.html')

def save(request):
	if request.method == "POST":
		mm = Member()
		mm.full_name = request.POST['full_name']
		mm.email = request.POST['email']
		mm.gender = request.POST['gender']
		mm.date_birth = request.POST['date_birth']
		mm.phone_number = request.POST['phone_number']
		mm.address = request.POST['address']
		mm.town_city = request.POST['town_city']
		mm.country = request.POST['country']
		mm.occupation = request.POST['occupation']
		mm.pics = request.FILES['image']
		mm.save()

	return render(request, 'stori/congrats.html')


def congrats(request):
	return render(request, 'stori/congrats.html')


def account(request):
	return render(request, 'stori/account.html')

def login(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/main/')
    return render_to_response('login.html', context_instance=RequestContext(request))

# @login_required(login_url='/login/')
# def main(request):










stori/templates/stori/account.html
<!Doctype html>
<html>
	<p>happy</p>


</html>

stori/templates/stori/base.html
{% extends 'stori/index.html' %}
{% load static from staticfiles %}


{% block body %}		
	    
		

    	

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="{% static 'images/691.jpg' %}" alt="Los Angeles" style="width:1700px; height: 900px;">
         <div class="carousel-caption" style="color: blue;">
          <h1>When the revelation drops</h1>
          
        </div> 
      </div>

      <div class="item">
        <img src="{% static 'images/566.jpg' %}" alt="Chicago" style="width:1700px; height: 900px;">
         <div class="carousel-caption">
          <h1>An honor to sit under the ministration of the man of God</h1>
          
        </div> 
      </div>
    
      <div class="item">
        <img src="{% static 'images/773.jpg' %}" alt="New York" style="width:1700px; height: 900px;">
         <div class="carousel-caption">
          <h1>We are family</h1>
          
        </div> 
      </div>

      <div class="item">
        <img src="{% static 'images/718.jpg' %}" alt="New York" style="width:1700px; height: 900px;">
         <div class="carousel-caption">
          <h1>The uponess of the Spirit</h1>
          
        </div> 
      </div>

      <div class="item">
        <img src="{% static 'images/921.jpg' %}" alt="New York" style="width:1700px; height: 900px;">
         <div class="carousel-caption">
          <h1>The time for worship and praises</h1>
          
        </div> 
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


	<h2 style="text-align:center; font-family: Palatino;"> WELCOME TO STORI'S MEMBERSHIP PLATFORM </h2><br>


	<p><h4 style="text-align:center; font-family: Palatino;"> This platform is to help all members identify with us and to signify that indeed they are part of this glorious and wonderful family(STORI).</h4></p><br>

	<p><h4 style="text-align:center; font-family: Palatino;">  If you have not yet registered and you desire to be a member then please register with us by clicking on the register link below.</h4></p><br>

	<a href="{% url 'stori:register' %}"><h3 style="font-family: Palatino; text-align:center;">Register</h3></a><br><br>


	<p><h4 style="text-align:center; font-family: Palatino;"> YOU ARE BLESSED, SHALOM.</h4></p></h4><br><br><br>


	
	
	

{% endblock %}





stori/templates/stori/congrats.html
{% extends 'stori/base.html' %}


{% load staticfiles %}

<title>Succesful</title>
{% block body %}

<body style="background-image: url("static/image/stori.jpg");>
<h1 style="text-align: center;">!!!CONGRATULATIONS!!!</h1><br>

<h3>You are now a member of STORI. You are a <strong>storian</strong></h3><br><br><br><br><br><br><br><br><br>


<h4 style="text-align:center">WELCOME TO THE FAMILY, SHALOM.</h4></h3><br><br><br><br><br><br><br><br><br><br><br>
</body>

{% endblock %}

stori/templates/stori/forms.html


{% for field in form %}
	<div class="form-group">
		<span class="text-danger small">{{ field.errors }}</span>
	</div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10">{{ field }}</div>
{% endfor %}

stori/templates/stori/index.html

{% load static from staticfiles %}


<!doctype html>
<html lang="en">

<head>
    	
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    

	    <title>Membership Platform</title>
	    


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>	
<link rel="stylesheet" type="text/css" href="/static/style.css"/>
{% block css%}

{% endblock %}
	
</head>

<body>
<div class="navbar navbar-inverse" style="height: 7pc;"">
 		<div class="container-fluid">
 			<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		        </button>

		         		

			     	<a class="navbar-brand" href="{% url 'stori:index' %}"><h1>STORI</h1></a>



			        <img src="{% static '/images/new logo 2.png' %}" style="float: right; width: 100px; height: 100px;"> 
			    	

			</div>
		</div>   
	
	{% block body %}



	{% endblock %}

	<div style="background-color: #454545; width: 100%; height: 405px; padding: 10px;"> 
		<h1 style="text-align:center; color: white; font-family: Palatino;">
	 	STORI - CHAMPIONING THE COURSE OF SONSHIP
		</h1>
	</div>
 	   

</body>
</html>


stori/templates/stori/register.html
{% extends 'stori/index.html' %}
{% load static from staticfiles %}


<head>
	{% block css %}
	<link rel="stylesheet" type="text/css" href="/static/register.css"/>
	{% endblock %}
</head>


	{% block body %}
	<br>
	<div>	
		<form action="{% url 'stori:save' %}" method="post"  name="form_name" enctype="multipart/form-data">
		{% csrf_token %}
		
		
			<input type="text" placeholder="Full name" name="full_name" required style="width: 350px; font-family: Palatino;"><br><br>
								
			<input type="text" placeholder="Email" name="email" style="width: 350px; font-family: Palatino;"><br><br>
							    
			<!-- <input type="radio" id="male" name="gender"><label for="male">Male</label><br>
			<input type="radio" id="female" name="gender"><label for="male">Female</label><br><br> -->

			<input list="gender" name='gender' type="text" placeholder="Gender" style="width: 350px; font-family: Palatino;">
 
			<datalist id="gender">
		    	<option>Male</option>
				<option>Female</option>
			</datalist><br><br>
	 
	 							
			<input id="date" type="date" placeholder="Date of birth" name="date_birth" style="width: 350px; font-family: Palatino;"><br><br>
									
			<input type="text" placeholder="Phone number" name="phone_number" style="width: 350px; font-family: Palatino;"><br><br>
								
			<input type="text" placeholder="Address" name="address" style="width: 350px; font-family: Palatino;"><br><br>
								
			<input type="text" placeholder="Town/City" name="town_city" style="width: 350px; font-family: Palatino;"><br><br>
								
			<input type="text" placeholder="Country" name="country" style="width: 350px; font-family: Palatino;"><br><br>
								
			<input type="text" placeholder="Occupation" name="occupation" style="width: 350px; font-family: Palatino;"><br><br>

			<p>Add your picture:</p>
			<input id ="id_image" type="file" name="image" placeholder="upload image"><br><br>

	    	<button type="submit" name="submit_name" id="btn_name" value="Submit" style="width: 350px; font-family: Palatino;">Submit</button>
			{% include 'stori/forms.html' %}	
		</form>
	</div>

	{% endblock %}
	

stori/templates/stori/signup.html
{% extends 'stori/base.html' %}

{% block body %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <p>
     	{% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
    	{% endfor %}
    </p>   
    <button type="submit">Sign up</button>
  </form>
{% endblock %}